# Stateful Code Analyzer - Generated Script
# Auto-generated from rules on {{GENERATION_DATE}}
#
# USAGE INSTRUCTIONS:
# 1. Place this script in your PROJECT ROOT directory (same level as .csproj/.sln for .NET or pom.xml/build.gradle for Java)
# 2. Run in PowerShell: .\analyze.ps1
# 3. Optional: Specify custom output path: .\analyze.ps1 -OutputPath "C:\custom\path\analysis.json"
#
# OUTPUT FILE:
# - stateful-analysis.json: Upload this file to the web application for detailed analysis and recommendations
#   (Contains only raw findings - recommendations and actions are generated by the backend)
#
# REQUIREMENTS:
# - PowerShell 5.0 or later
# - Project must be .NET (*.csproj, *.sln) or Java (pom.xml, build.gradle)

param([string]$OutputPath = $null)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$OutputFile = if ($OutputPath) { $OutputPath } else { Join-Path $ScriptDir "stateful-analysis.json" }
$TempFindings = Join-Path $ScriptDir ".findings_temp.json"

Write-Host "╔═══════════════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║   Stateful Code Analyzer v2.0                ║" -ForegroundColor Blue  
Write-Host "║   Generated with {{RULES_COUNT}} rules                     ║" -ForegroundColor Blue
Write-Host "╚═══════════════════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""

# Detect project type
$ProjectType = "unknown"
if ((Test-Path "*.csproj") -or (Test-Path "*.sln") -or (Get-ChildItem -Recurse -Filter "*.csproj" -Depth 3)) {
    $ProjectType = "dotnet"
    Write-Host "✓ Detected .NET project" -ForegroundColor Green
} elseif ((Test-Path "pom.xml") -or (Test-Path "build.gradle")) {
    $ProjectType = "java" 
    Write-Host "✓ Detected Java project" -ForegroundColor Green
} else {
    Write-Host "✗ Could not detect project type" -ForegroundColor Red
    exit 1
}

# Initialize findings
@() | ConvertTo-Json | Out-File -FilePath $TempFindings -Encoding UTF8

# Add finding function
function Add-Finding {
    param([string]$File, [string]$Function, [int]$LineNum, [string]$Code, [string]$Category, [string]$Severity, [string]$Remediation)
    
    $finding = @{
        filename = $File
        function = $Function
        lineNum = $LineNum
        code = $Code
        category = $Category
        severity = $Severity
        remediation = $Remediation
    }
    
    $current = Get-Content $TempFindings | ConvertFrom-Json
    $current += $finding
    $current | ConvertTo-Json -Depth 10 | Out-File -FilePath $TempFindings -Encoding UTF8
}

# Get function name
function Get-FunctionName {
    param([string]$FilePath, [int]$LineNum)
    
    $start = [Math]::Max(1, $LineNum - 30)
    $lines = Get-Content $FilePath
    
    for ($i = $LineNum - 1; $i -ge $start - 1; $i--) {
        if ($lines[$i] -match '(public|private|protected|internal).*\s+(\w+)\s*\(') {
            return $matches[2]
        }
    }
    return "Unknown"
}

# .NET Analysis
function Analyze-DotNet {
    Write-Host "Analyzing .NET code..." -ForegroundColor Yellow
    $totalFiles = 0
    $issuesFound = 0
    
    $csFiles = Get-ChildItem -Recurse -Filter "*.cs" | Where-Object { $_.FullName -notmatch '\\(bin|obj|packages|\\.vs)\\' }
    
    foreach ($file in $csFiles) {
        $totalFiles++
        $relativeFile = $file.FullName.Replace("$ScriptDir\", "")
        $content = Get-Content $file.FullName
        
{{DOTNET_PATTERNS}}
        
        Write-Progress -Activity "Scanning .NET files" -Status "Scanned: $totalFiles files, Found: $issuesFound issues" -PercentComplete (($totalFiles / $csFiles.Count) * 100)
    }
    
    Write-Host ""
    Write-Host "✓ .NET analysis complete" -ForegroundColor Green
}

# Java Analysis
function Analyze-Java {
    Write-Host "Analyzing Java code..." -ForegroundColor Yellow
    $totalFiles = 0
    $issuesFound = 0
    
    $javaFiles = Get-ChildItem -Recurse -Filter "*.java" | Where-Object { $_.FullName -notmatch '\\(target|build|\\.idea)\\' }
    
    foreach ($file in $javaFiles) {
        $totalFiles++
        $relativeFile = $file.FullName.Replace("$ScriptDir\", "")
        $content = Get-Content $file.FullName
        
{{JAVA_PATTERNS}}
        
        Write-Progress -Activity "Scanning Java files" -Status "Scanned: $totalFiles files, Found: $issuesFound issues" -PercentComplete (($totalFiles / $javaFiles.Count) * 100)
    }
    
    Write-Host ""
    Write-Host "✓ Java analysis complete" -ForegroundColor Green
}

# Run analysis
if ($ProjectType -eq "dotnet") {
    Analyze-DotNet
} elseif ($ProjectType -eq "java") {
    Analyze-Java
}

# Create output
$findings = Get-Content $TempFindings | ConvertFrom-Json
$analysis = @{
    projectType = $ProjectType
    scanDate = (Get-Date -Format o)
    rootPath = $ScriptDir
    findings = $findings
}

$analysis | ConvertTo-Json -Depth 10 | Out-File -FilePath $OutputFile -Encoding UTF8

# Cleanup
Remove-Item $TempFindings -ErrorAction SilentlyContinue

# Summary
$totalIssues = $findings.Count
Write-Host ""
Write-Host "╔═══════════════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║           Analysis Complete!                  ║" -ForegroundColor Blue
Write-Host "╚═══════════════════════════════════════════════╝" -ForegroundColor Blue
Write-Host "✓ Output: $OutputFile" -ForegroundColor Green
Write-Host "✓ Issues found: $totalIssues" -ForegroundColor Green
Write-Host ""